
trigger:
  paths:
   include:
      - '*.ipynb'
      - '**/*.ipynb'
  branches:
    exclude:
      - 'main'

pool:
  vmImage: ubuntu-latest

variables:
  TARGET_BRANCH: 'origin/main'
  REPO_URL: 'dev.azure.com/risquass/test-jupyter2/_git/test-jupyter2'

steps:

- script: |
    python -m pip install --upgrade pip
  displayName: 'Upgrade pip'

- script: |
    pip install nbconvert ipython
  displayName: 'install nbconvert & ipython'

- script: |
    sudo apt install -y pandoc
  displayName: "Install pandoc"

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      git fetch https://$(System.AccessToken)@$(REPO_URL)
      git branch -r
      IPYNB_PATH=($(git diff --name-only --diff-filter=AD origin/$(Build.SourceBranchName)..$(TARGET_BRANCH) -- | grep '[.]ipynb$'))
      [ -z "$IPYNB_PATH" ] && echo "Nothing to convert" || jupyter nbconvert --to script $IPYNB_PATH
  displayName: "Convert Notebook to script"

- bash: | 
    git config --global user.email "build@dev.azure.com"
    git config --global user.name "build"
    git add .
    git commit -m 'Convert Jupyter notebooks' || echo "No changes to commit" && NO_CHANGES=1
    [ -z "$NO_CHANGES" ] || git push https://$(System.AccessToken)@$(REPO_URL) HEAD:$(Build.SourceBranchName)
  displayName: "Commit notebook to repository"
