# MD004 - Unordered list style
ul-style: false

# MD007 - Unordered list indentation
ul-indent:
  indent: 2

# MD013 - Line length
line-length: false

# MD026 - Trailing punctuation in header
no-trailing-punctuation:
  punctuation: ".,;:!。，；:"

# MD029 - Ordered list item prefix
ol-prefix: false

# MD033 - Inline HTML
no-inline-html: false

# MD036 - Emphasis used instead of a header
no-emphasis-as-header: false

# MD012 - Multiple consecutive blank lines
# MD022 - Headers should be surrounded by blank lines
# MD031 - Fenced code blocks should be surrounded by blank lines
# MD032 - Lists should be surrounded by blank lines
# MD047 - File should end with a single newline character
blank_lines: false
