---
# Configuration file for MegaLinter
# See all available variables at https://megalinter.io/latest/config-file/ and in linters documentation

APPLY_FIXES: all # all, none, or list of linter keys
# ENABLE: # If you use ENABLE variable, all other languages/formats/tooling-formats will be disabled by default
# ENABLE_LINTERS: # If you use ENABLE_LINTERS variable, all other linters will be disabled by default
ENABLE_LINTERS:
  - ACTION_ACTIONLINT
  - MARKDOWN_MARKDOWNLINT
  - MARKDOWN_MARKDOWN_TABLE_FORMATTER
  - SPELL_CSPELL
  - YAML_PRETTIER
  - YAML_YAMLLINT
  - SPELL_LYCHEE

SPELL_CSPELL_DISABLE_ERRORS: true
SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PARALLEL: true
GITHUB_STATUS_REPORTER: true
LOG_LEVEL: WARNING
MARKDOWN_MARKDOWN_TABLE_FORMATTER_ARGUMENTS: "-c"
# DISABLE_ERRORS: true # Uncomment if you want MegaLinter to detect errors but not block CI to pass
