graph LR
    A[Diagram Idea] -->|Write mermaid code| B(mermaid.mmd file)
    B -->|Add to source control| C{Code repo}
    B -->|Export as .png| G(.png file of diagram)
    G -->|Add to source control| C